# Generated by Django 6.0 on 2025-12-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_username', models.CharField(max_length=30, unique=True)),
                ('u_email', models.EmailField(max_length=30, unique=True)),
                ('u_password', models.CharField(max_length=24)),
                ('u_confirm', models.CharField(max_length=24)),
            ],
        ),
    ]
