# Generated by Django 6.0 on 2025-12-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_model',
            name='u_confirm',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='reg_model',
            name='u_password',
            field=models.CharField(),
        ),
    ]
