# Generated by Django 6.0 on 2025-12-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_reg_model_u_confirm_alter_reg_model_u_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_model',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
