# Generated by Django 6.0 on 2025-12-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_reg_model_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_model',
            name='u_confirm',
            field=models.CharField(blank=True, null=True),
        ),
    ]
