# Generated by Django 6.0 on 2025-12-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_reg_model_u_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_model',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
