# Generated by Django 6.0 on 2025-12-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_reg_model_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_model',
            name='u_username',
            field=models.CharField(max_length=30),
        ),
    ]
