# Generated by Django 6.0 on 2025-12-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_reg_model_u_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('course_desc', models.TextField()),
                ('course_price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='reg_model',
            name='u_course',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.course_model'),
        ),
    ]
