# Generated by Django 6.0 on 2025-12-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_course_model_reg_model_u_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_model',
            name='u_course',
            field=models.ManyToManyField(blank=True, to='myapp.course_model'),
        ),
    ]
