# Generated by Django 6.0 on 2025-12-22 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_reg_model_u_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg_model',
            name='u_course',
        ),
        migrations.AddField(
            model_name='reg_model',
            name='u_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.course_model'),
        ),
    ]
