# Generated by Django 6.0 on 2025-12-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_reg_model_u_course_reg_model_u_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_model',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], default=None, max_length=20, null=True),
        ),
    ]
