# Generated by Django 6.0 on 2025-12-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_reg_model_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_model',
            name='activation_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
