# Generated by Django 6.0 on 2025-12-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_reg_model_activation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_model',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reg_model',
            name='pre_role',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
