# Generated by Django 6.0 on 2025-12-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_reg_model_is_active_reg_model_pre_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_model',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
